---
title: aaramirez.github.io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: inner
source: "."
destination: "./_site"
plugins_dir: "./_plugins"
layouts_dir: "./_layouts"
data_dir: "./_data"
safe: false
include:
- _pages
exclude: []
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
show_drafts:
limit_posts: 0
future: true
unpublished: false
whitelist: []
gems:
- jekyll-paginate
plugins: [jekyll-paginate]
lsi: false
excerpt_separator: "\n\n"
detach: false
port: 4000
host: 127.0.0.1
baseurl: ''
permalink: none
paginate: 5
paginate_path: "/page:num"
quiet: false
rdiscount:
  extensions: []
redcarpet:
  extensions: []
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: javascript
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
url: https://aaramirez.github.io
