---
title: alexanderramirez.me
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: inner
source: "."
destination: "./_site"
plugins_dir: "./_plugins"
layouts_dir: "./_layouts"
data_dir: "./_data"
safe: false
include:
- _pages
exclude: []
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
show_drafts:
limit_posts: 0
future: true
unpublished: false
whitelist: []
gems:
- jekyll-paginate
plugins: [jekyll-paginate]
markdown: kramdown
lsi: false
excerpt_separator: "\n\n"
detach: false
port: 4000
host: 127.0.0.1
baseurl: ''
permalink: none
paginate: 5
paginate_path: "/page:num"
quiet: false
rdiscount:
  extensions: []
redcarpet:
  extensions: []
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter_opts:
    wrap: div
    line_numbers: inline
    line_number_start: 1
    tab_width: 4
    bold_every: 10
    css: style
url: http://alexanderramirez.me
