# Site settings
title: Volver al futuro...
email: timoto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Compartir algo de lo que pienso, aprendo y hago, relacionado con la vida, la tecnología,
  las aplicaciones, desarrollo de software, especulación, inversiones y finanzas.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexanderamirez.me" # the base hostname & protocol for your site
twitter_username: aaramirez
github_username:  aaramirez
# Additional settings
safe: true
timezone: America/Caracas
# Build settings
markdown: kramdown
#highlighter: pygments
# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Alexander A. Ramírez M."
