# Site settings
title: Back to the future...
email: timoto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Experiencias desarrollando servicios que valgan la pena usar. Algunos tutoriales 
  para ayudarme a mi mismo a dominar la tecnología.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aaramirez.github.io" # the base hostname & protocol for your site
twitter_username: @aaramirez
github_username:  aaramirez

# Build settings
markdown: kramdown
